components:
  schemas:
    DeletedUrllist:
      properties:
        data:
          properties:
            type:
              enum:
                - exact
                - regex
              type: string
            urls:
              items:
                example: www.test.com
                type: string
              type: array
          type: object
        id:
          format: int64
          type: integer
        modify_by:
          example: Netskope API
          type: string
        modify_time:
          example: "1997-01-01 00:00:00"
          type: string
        modify_type:
          example: Deleted
          type: string
        name:
          type: string
        pending:
          example: 1
          type: integer
      type: object
    UrllistRequest:
      x-speakeasy-entity: URLList
      properties:
        data:
          properties:
            type:
              enum:
                - exact
                - regex
              type: string
            urls:
              items:
                example: www.test.com
                type: string
              type: array
          type: object
        name:
          type: string
      type: object
    UpdatedUrllist:
      properties:
        data:
          properties:
            type:
              enum:
                - exact
                - regex
              type: string
            urls:
              items:
                example: www.test.com
                type: string
              type: array
          type: object
        id:
          format: int64
          type: integer
        modify_by:
          example: Netskope API
          type: string
        modify_time:
          example: "1997-01-01 00:00:00"
          type: string
        modify_type:
          example: Edited
          type: string
        name:
          type: string
        pending:
          example: 1
          type: integer
      type: object
    Urllist:
      x-speakeasy-entity: URLList
      properties:
        data:
          properties:
            type:
              enum:
                - exact
                - regex
              type: string
            urls:
              items:
                example: www.test.com
                type: string
              type: array
          type: object
        id:
          format: int64
          type: integer
        modify_by:
          example: Netskope API
          type: string
        modify_time:
          example: "1997-01-01 00:00:00"
          type: string
        modify_type:
          enum:
            - Created
            - Edited
            - Deleted
          type: string
        name:
          type: string
        pending:
          type: integer
      type: object
info:
  description: "URL list management API"
  title: "URL List"
  version: "1.0.0"
openapi: 3.0.0
paths:
  /policy/urllist:
    get:
      operationId: listURLLists
      x-speakeasy-name-override: list_objects
      x-speakeasy-entity-operation: URLListList#read
      x-speakeasy-group: URLList
      description:
        Returns an array of URL list objects containing ID, name, URLs,
        type, modify type, modify by, modify time, and pending information.
      parameters:
        - description: Get a list of only applied (0) or pending (1) URL lists
          in: query
          name: pending
          required: false
          schema:
            enum:
              - 0
              - 1
            type: number
          x-speakeasy-ignore: true
        - description: Data values to return in response call. Defaults to all values
          in: query
          name: field
          required: false
          schema:
            enum:
              - id
              - name
              - data
              - modify_type
              - modify_time
              - modify_by
              - pending
            type: string
          x-speakeasy-ignore: true
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Urllist"
                type: array
          description: Succesfully got URL lists
      summary: Get all applied and pending URL lists
    post:
      operationId: createURLList
      x-speakeasy-name-override: create
      x-speakeasy-entity-operation: URLList#create
      x-speakeasy-group: URLList
      description: Create a new URL list configuration
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UrllistRequest"
        description: New URL list object
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Urllist"
          description: successful operation
      summary: Create a new URL list.
    x-netskope-params:
      apiGroup: urllist
      customerFacing: true
      serviceConfig: webui-api
      version: 2
  /policy/urllist/deploy:
    post:
      x-speakeasy-ignore: true
      description: Applies currently pending changes for URL lists.
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Urllist"
                type: array
          description: Succesfully deployed URL lists
      summary: Apply pending URL list changes.
    x-netskope-params:
      apiGroup: urllist
      customerFacing: true
      serviceConfig: webui-api
      version: 2
  /policy/urllist/file:
    post:
      x-speakeasy-ignore: true
      description:
        "Upload multiple URL list configurations via a JSON file."
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                urllist:
                  format: binary
                  type: string
              type: object
        description: JSON file with URL list configurations
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Urllist"
          description: successful operation
      summary: Upload multiple configurations via a JSON file
    x-netskope-params:
      apiGroup: urllist
      customerFacing: true
      serviceConfig: webui-api
      version: 2
  /policy/urllist/{id}:
    delete:
      operationId: deleteURLList
      x-speakeasy-name-override: delete
      x-speakeasy-entity-operation: URLList#delete
      x-speakeasy-group: URLList
      description: Mark a URL list as pending deletion.
      parameters:
        - description: ID of the URL list
          in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeletedUrllist"
          description: successful operation
      summary: Delete a URL list.
    get:
      operationId: getURLList
      x-speakeasy-name-override: read
      x-speakeasy-entity-operation: URLList#read
      x-speakeasy-group: URLList
      description: Get the configuration of the given URL list ID.
      parameters:
        - description: ID of the URL list
          in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Urllist"
          description: successful operation
      summary: Get URL list by ID.
    put:
      operationId: updateURLList
      x-speakeasy-name-override: update
      x-speakeasy-entity-operation: URLList#update
      x-speakeasy-group: URLList
      description: Completely replace the configuration of the given URL list ID.
      parameters:
        - description: ID of the URL list
          in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UrllistRequest"
        description: New URL list object
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdatedUrllist"
          description: successful operation
      summary: Replace a URL list configuration.
    x-netskope-params:
      apiGroup: urllist
      customerFacing: true
      serviceConfig: webui-api
      version: 2
  /policy/urllist/{id}/{action}:
    patch:
      x-speakeasy-ignore: true
      description: Update name, URLs, and/or type of URL list object
      parameters:
        - description: ID of the URL list
          in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
        - description: Replace or append to current URLs
          in: path
          name: action
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UrllistRequest"
        description: New URL list object
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdatedUrllist"
          description: successful operation
      summary: Patch URL list
    x-netskope-params:
      apiGroup: urllist
      customerFacing: true
      serviceConfig: webui-api
      version: 2
